Add friends likes
ebogacheva/java-filmorate pull request #3
Opened 2023-04-03 19:38 UTC by ebogacheva

2023-04-04 14:45 UTC, Fleaman777 requested changes

2023-04-04 14:45 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService filmService;
поля должны быть private

относится ко всем похожим местам

2023-04-04 14:45 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private final HashMap<Integer, Film> films = new HashMap<>();
тип поля лучше сделать более широким Map, 
так полиморфизм будет работать лучше, 
в случае, если вдруг поменяется реализация хранения films на другой тип Map, не придется делать много исправлений в коде

2023-04-04 15:13 UTC, ebogacheva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService filmService;
Исправила.

2023-04-04 15:27 UTC, ebogacheva commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private final HashMap<Integer, Film> films = new HashMap<>();
ок! спасибо.

2023-04-05 13:04 UTC, Fleaman777 approved these changes

2023-04-15 08:19 UTC, merged